[package]
edition = "2021"
name = "cliclack"
version = "0.1.0"

[dependencies]
console = "0.15.7"
indicatif = "0.17.5"
once_cell = "1.18.0"
textwrap = "0.16.0"
zeroize = {version = "1.6.0", features = ["derive"]}
