[package]
name = "cliclack"
version = "0.1.0"

authors = ["Alexander Fadeev <fadeevab.com@gmail.com>"]
categories = ["command-line-interface"]
description = "Beautiful opinionated CLI prompts for Rust ported from @clack/prompts npm package."
edition = "2021"
keywords = ["cli", "command-line", "terminal", "console"]
license = "MIT"
readme = "README.md"

[dependencies]
console = "0.15.7"
indicatif = "0.17.5"
once_cell = "1.18.0"
textwrap = "0.16.0"
zeroize = {version = "1.6.0", features = ["derive"]}
