[package]
edition = "2021"
name = "claquer"
version = "0.1.0"

[dependencies]
console = "0.15.7"
dialoguer = { path = "../../dialoguer" }
once_cell = "1.18.0"

[dev-dependencies]
console = "0.15.7"
dialoguer = {path = "../../dialoguer"}
